name: GitHub Metrics

on:
  # 1. প্রতিদিন রাত ১২টায় অটোমেটিক রান হবে
  schedule:
    - cron: "0 0 * * *"
  # 2. আপনি চাইলে ম্যানুয়ালি রান করতে পারবেন
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # আপনার টোকেন
          token: ${{ secrets.METRICS_TOKEN }}

          # আপনি যা যা দেখতে চেয়েছেন
          user: SajidHossainKhan01
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 20
